pam_sss: fix missing initializer warning
src/sss_client/pam_sss.c: In function ‘prompt_sc_pin’:
src/sss_client/pam_sss.c:1865:41: error: missing initializer for field ‘prev’ of ‘struct cert_auth_info’ [-Werror=missing-field-initializers]
 1865 |                                         NULL, NULL, NULL, NULL, NULL, NULL };

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>